apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
spec:
  type: ClusterIP
  ports:
    - name: kube-state-metrics
      port: 8080
    - name: metrics
      port: 8081
  selector:
    app.kubernetes.io/name: kube-state-metrics
